# vortex-gitops/values.yaml
appName: "vortex"
replicaCount: 2

image:
  repository: mangeshforstudy/vortex
  # Jenkins will automatically overwrite this tag value on every pipeline run
  tag: "1.3.0-build-15"
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 8083
  targetPort: 80
